const PROVIDERS = {
  SETTINGS: 'SETTINGS_REPOSITORY',
  USER: 'USER_REPOSITORY',
  CASE: 'CASE_REPOSITORY',
  EXHIBIT: 'EXHIBIT_REPOSITORY',
  DECISION: 'DECISION_REPOSITORY',
  NOTICE: 'NOTICE_REPOSITORY',
  PETITION: 'PETITION_REPOSITORY',
  VERDICT: 'VERDICT_REPOSITORY',
  DEPOSIT_VOUCHER: 'DEPOSIT_VOUCHER_REPOSITORY',
  CLAIM: 'CLAIM_REPOSITORY',
  FILE: 'FILE_REPOSITORY',
};
export default PROVIDERS;
